---
# tasks file for configure-obsidian
- name: "Download the deb Obsidian package"
  get_url:
    url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.3.5/obsidian_1.3.5_amd64.deb"
    dest = "{{ role_path }}/files/obsidian.deb"
- name: "Install the package"
  dpkg_selections:
    name: obsidian
    selection: deinstall
  become: true
  become_method: sudo
