---
# master playbook file
- hosts: all
  user: kali
  become: yes
  become_user: root
  vars:
    hostvar: install
  roles:
    - { role: metadata, tags: always }
    - { role: tmux, tags: tmux }
    - { role: zsh, tags: zsh }
    - { role: firefox, tags: firefox }
    - { role: obisidian, tags: obsidian }
    - { role: structure, tags: struture }
