---
# master playbook file
- name: "Kali attackbox"
  hosts: all
  vars:
    hostvar: install
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/configure-obsidian"
    - role: "roles/configure-shell"
    - role: "roles/configure-structure"
#    - role: "roles/configure-firefox"
