---
# master playbook file
- name: "Kali attackbox"
  hosts: localhost
  #hosts: '{{ latitude | default("") }}'
  roles:
#    - role: "roles/configure-tmux"
#    - role: "roles/configure-obsidian"
    - role: "roles/configure-terminal"
#    - role: "roles/configure-structure"
#    - role: "roles/configure-firefox"
#    - role: "roles/configure-shell"