---
# playbook file
- name: "Kali attackbox"
  hosts: latitude
  #hosts: '{{ latitude | default("localhost") }}'
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/configure-obsidian"
    - role: "roles/configure-terminal"
    - role: "roles/configure-structure"
#    - role: "roles/configure-shell"