---
# install file for configure-structure
- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/thm"
    - "{{ ansible_env.HOME }}/thm/vpn"
    - "{{ ansible_env.HOME }}/htb"
    - "{{ ansible_env.HOME }}/htb/vpn"
    - "{{ ansible_env.HOME }}/tools"
