---
# tasks file for configure-structure
- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/ecsc"
    - "{{ ansible_env.HOME }}/tools"