---
# uninstall file for configure-structure
- name: "Remove directories"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/ecsc"
    - "{{ ansible_env.HOME }}/tools"